Naver, Google, Kakao 소셜 로그인 추가
DDD-6/hermes-server pull request #4
Opened 2021-10-30 07:23 UTC by Mactto

DB에 저장되는 id는 각 API의 유저 ID로 설정하였습니다!
엑세스 토큰을 완료한 후 비니지스 로직에서 기존에 존재하는 유저인지 검사 후
새로운 유저일 경우 DB에 저장한 후 엑세스 토큰을 반환하는 방향으로 구현하였습니다!

혹시 구현 방식이나 컨벤션 관련해서 문제가 있으면 언제든 편하게 말씀해주세요~
확인해주시고 merge 부탁드리겠습니다!

2021-11-02 00:19 UTC, changhoi requested changes
- package-lock.json이 계속 생기는 거 보니까 npm을 더 애용하시는 것 같은데, 그걸로 할까요? 둘 다 있으면 안될 것 같아서요!
- configs 모듈에서 만들어서 환경변수 써주세요. 도커 컴포즈에서 env file 불러오는 구조라 config 모듈 따로 필요 없는데, 혹시 도커 사용 안하고 개발 중이신가요?
- 제가 백앤드로 소셜로그인 할 때는 클라이언트에서 로그인 해서 받은 정보를 백엔드가 받아주는 구조였는데, 이렇게 해도 리액트 페이지로 돌아가서 토큰 활용 되나요?

2021-11-02 00:19 UTC, changhoi commented on src/core/configs/configs.module.ts
> +  imports: [ConfigModule.forRoot()],
도커컴포즈에 env file로 들어가서 이게 딱히 필요 없지 않나요?

2021-11-02 00:19 UTC, changhoi commented on src/entities/user.entity.ts
> +    created_at: Date;
camelCase로 작성해주세요!

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/strategies/naver.strategy.ts
> +            callbackURL: "http://localhost:3000/authentication/naver/callback",
configs 사용해서 넣어주세요.

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/strategies/kakao.strategy.ts
> +        done(null, user);
리턴타입이 없어도 될 것 같아요. 프로필 타입은 알 수 없나요?

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/strategies/jwt.strategy.ts
> +            secretOrKey: process.env.JWT_SECRET,
configs 모듈 사용

2021-11-02 00:19 UTC, changhoi commented on src/entities/user.entity.ts
> +    id: string;
로그인 할 때 appID를 여기에 넣으시는 건가요? 소셜로그인 여러 개를 붙일 때는 어떻게 되나요? 여러 아이디 연결하는 기능이요!

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/strategies/google.strategy.ts
> +            callbackURL: 'http://localhost:3000/authentication/google/callback',
configs 모듈 사용

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/auth.service.ts
> +            console.log(err);
로그 지워주세요! 로그를 남기시려는 의도면 로거 사용해주세요

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/auth.service.ts
> +        try {
로직을 보니까 에러가 나면 그냥 다시 throw 해주는 것 같은데, 그러면 굳이 감싸지 않아도 될 것 같아요

2021-11-02 00:19 UTC, changhoi commented on src/api/auth/auth.module.ts
> +        }),
리프레시 사용 중이신가요? 만료되면 어떻게 동작하나요?

2021-11-02 12:38 UTC, Mactto commented
* package-lock.json이 계속 생기는 거 보니까 npm을 더 애용하시는 것 같은데, 그걸로 할까요? 둘 다 있으면 안될 것 같아서요!
-> yarn 사용하기로 했던 걸 정말 새까맣게 잊어버리고 있었네요.. yarn으로 바꿔놓겠습니다!

* configs 모듈에서 만들어서 환경변수 써주세요. 도커 컴포즈에서 env file 불러오는 구조라 config 모듈 따로 필요 없는데, 혹시 도커 사용 안하고 개발 중이신가요?
-> 도커 사용을 안해봐서 그냥 진행하고 있었습니다 ㅠㅠ 이번에 회사에서 도커 사용을 조금 해봐서 한 번 사용해보겠습니다!

* 제가 백앤드로 소셜로그인 할 때는 클라이언트에서 로그인 해서 받은 정보를 백엔드가 받아주는 구조였는데, 이렇게 해도 리액트 페이지로 돌아가서 토큰 활용 되나요?
-> 클라이언트 쪽에서 받는게 편하긴 합니다! 백엔드 쪽에서 받으면 콜백을 다시 클라이언트로 redirect 해줘야 해서 번거롭긴 하지만 프론트 쪽 일이 많을 것 같아서 일단 백에서 처리하긴 했습니다! 이 부분은 내일 회의 때 이야기해보면 좋겠습니다.

꼼꼼한 리뷰 너무 감사드립니다! 빼먹고 한 부분이 많았네요..
전부 수정해서 이번 주 내로 다시 PR 하겠습니다!

2021-11-02 12:38 UTC, Mactto commented on src/core/configs/configs.module.ts
> +  imports: [ConfigModule.forRoot()],
도커 사용해서 해보겠습니다!

2021-11-02 12:39 UTC, Mactto commented on src/entities/user.entity.ts
> +    created_at: Date;
넵 수정하겠습니다

2021-11-02 12:39 UTC, Mactto commented on src/api/auth/strategies/naver.strategy.ts
> +            callbackURL: "http://localhost:3000/authentication/naver/callback",
확인했습니다!

2021-11-02 12:39 UTC, Mactto commented on src/api/auth/strategies/kakao.strategy.ts
> +        done(null, user);
프로필 타입은 어떤 걸 말씀하시는 지 알 수 있을까요??

2021-11-02 12:40 UTC, Mactto commented on src/api/auth/strategies/jwt.strategy.ts
> +            secretOrKey: process.env.JWT_SECRET,
확인했습니다!

2021-11-02 12:41 UTC, Mactto commented on src/entities/user.entity.ts
> +    id: string;
소셜로그인에서 각 사용자의 고유한 ID를 넣는 필드로 사용하고 있습니다!
카카오, 네이버, 구글 상관없이 넣을 수 있어서 아이디를 연결하는 부분이 따로 있을까요?

2021-11-02 12:41 UTC, Mactto commented on src/api/auth/strategies/google.strategy.ts
> +            callbackURL: 'http://localhost:3000/authentication/google/callback',
확인했습니다!

2021-11-02 12:41 UTC, Mactto commented on src/api/auth/auth.service.ts
> +            console.log(err);
에러 확인해보다가 안지웠네요! 수정해놓겠습니다

2021-11-02 12:41 UTC, Mactto commented on src/api/auth/auth.service.ts
> +        try {
확인했습니다!

2021-11-02 12:42 UTC, Mactto commented on src/api/auth/auth.module.ts
> +        }),
따로 리프레시 저장 안하고 있습니다!
지금은 엑세스 토큰이 만료되면 다시 로그인하는 방법 밖에 없습니다.

2021-11-03 07:44 UTC, changhoi commented on src/api/auth/strategies/kakao.strategy.ts
> +        done(null, user);
<any> 타입이요!

2021-11-03 07:45 UTC, changhoi commented on src/entities/user.entity.ts
> +    id: string;
보통 연결하기 기능이라고 부르는 것들이 있잖아요, 하나의 아이디에 여러 개의 소셜 로그인이 가능하도록 만드는 방식으로요

2021-12-18 12:13 UTC, closed without merging